import type { BlogPost } from "@/lib/types";

const post: BlogPost = {
  slug: "citations-explained-bing-apple-maps-yelp",
  title: "Local Citations Explained: Bing, Apple Maps and Yelp",
  metaTitle: "Local Citations: Bing, Apple Maps, Yelp | Lucros Results",
  description:
    "Local citations explained for Los Angeles business owners: what they are, why Bing Places, Apple Maps and Yelp matter, and a simple one-afternoon plan.",
  date: "2026-10-03",
  body: [
    "Most owners put all their energy into Google. That makes sense, but Google is not the only place customers find you.",
    "Maps apps, voice assistants and review sites all pull business details from somewhere. If those details are missing or wrong, you lose customers you never knew you had.",
    "This guide explains **local citations** in plain English and gives you an afternoon plan to clean them up.",
    "## What is a citation?",
    "A citation is any mention of your business **name, address and phone number** on another website. A directory listing is the classic example. So is a profile on a review site or a map app.",
    "Citations do not need a link to your website. The details themselves are the point.",
    "Google's own guidance says local results come down to relevance, distance and prominence. Consistent, accurate listings across the web help show that you are a real, established business. We cover the details in our post on [what NAP is and why it matters](/blog/what-is-nap-and-why-it-matters-for-local-seo).",
    "## Why Bing, Apple Maps and Yelp matter beyond Google",
    "Plenty of people never open Google Maps. They use an iPhone and tap Apple Maps. They ask a voice assistant for a nearby plumber. They check Yelp before they book a restaurant or a salon.",
    "These platforms are also data sources. Other apps, in-car systems and assistants often pull business information from them. We will not pretend to know exactly which app uses which source, and it changes over time. The safe takeaway is simple: **wrong details in one place can follow you into several others**.",
    "- **Bing Places** feeds Bing search and Bing Maps, and is commonly used by other products too.\n- **Apple Maps** is the default map on every iPhone, and you manage it through Apple Business Connect.\n- **Yelp** is a major review destination, especially for restaurants, home services and personal care.",
    "Claiming all three is free, and it takes less time than most owners expect.",
    "## How to claim and fill them out",
    "The process is similar everywhere. Search for your business first, because a listing may already exist. Then claim it instead of creating a new one.",
    "- Bing Places: sign in, search for your business, and claim it. If your Google Business Profile is up to date, Bing offers a way to import it, which saves time. Check everything after the import.\n- Apple Business Connect: sign in with an Apple Account, search for your location, and claim it. Verification may take a call or a document, so allow some time.\n- Yelp: create or claim your business page through Yelp for Business, then confirm your ownership.",
    "On each one, fill out **every field you can**. Add your categories, hours, website, a short description and real photos of your storefront, team and work.",
    "Your Google profile should be your model. If you have not polished it yet, start with our [Google Business Profile optimization](/services/google-business-profile-optimization) service page and work outward from there.",
    "## Keep your NAP identical everywhere",
    "Pick one exact version of your name, address and phone number, and use it on every listing. Write it down in a note so you can copy and paste it.",
    "Small differences cause confusion. Say your sign reads Valley Air Heating and Cooling. Do not list it as \"VA Heating\" in one place and \"Valley Air HVAC LLC\" in another.",
    "Watch for these common slips:",
    "- Suite versus Ste versus Unit\n- Street versus St\n- An old phone number or a tracking number\n- A former address after a move\n- Extra keywords stuffed into the business name",
    "Use the same website address everywhere too. Pick one version and stick with it.",
    "## Avoid junk directories",
    "More listings are not always better. Some sites are low quality, packed with ads, or exist only to sell you paid upgrades.",
    "Focus on the trusted platforms first: Google, Bing, Apple, Yelp and the major social profiles. After that, add listings that fit your trade or your area, such as an industry association or your local chamber of commerce.",
    "A good test is simple. Would a real customer plausibly look for you there? If not, skip it.",
    "Be cautious with anyone who promises to blast your business onto hundreds of directories. Bulk submissions can leave you with messy, hard-to-fix listings.",
    "## How to find and fix duplicates",
    "Duplicates happen when a business moves, changes its name, or gets listed by a data provider without your input. They split your reviews and confuse customers.",
    "Here is how to hunt them down:",
    "- Search your business name plus your city on Google, Bing and Yelp.\n- Search your phone number and your old address.\n- Look for listings with outdated names, hours or locations.",
    "When you find one, claim it if you can, then update it to match your master NAP. If it is a true duplicate, use the platform's report or merge option instead of leaving it alone. If you moved, mark the old location as closed or update it, depending on what the platform allows.",
    "Be patient. Changes can take days or longer to show up. Keep a simple note of what you submitted and when.",
    "## Your one-afternoon plan",
    "You do not need a week for this. Set aside a few focused hours and work through these steps.",
    "- Write your master NAP, categories, hours and a short description.\n- Check your Google Business Profile for accuracy.\n- Claim Bing Places and confirm the details.\n- Claim Apple Business Connect and add photos.\n- Claim Yelp and complete the profile.\n- Search for duplicates and old details, then fix or report them.\n- Save a list of every login in a secure place.",
    "Then set a reminder to review everything twice a year, or any time you change your hours, phone or address.",
    "## Where to go from here",
    "Citations are the foundation, not the whole house. They work best alongside a strong profile, good reviews and a website that matches your listings. That is the heart of our [local SEO](/services/local-seo) work for Los Angeles businesses.",
    "Not sure where your listings stand? Book a [free strategy call](/contact) and we will help you spot the gaps.",
  ],
};

export default post;
