import type { BlogPost } from "@/lib/types";

const post: BlogPost = {
  slug: "google-business-profile-checklist-for-los-angeles-businesses",
  title: "Google Business Profile Checklist for Los Angeles Businesses",
  metaTitle: "Google Business Profile Checklist for Los Angeles | Lucros",
  description:
    "Use this Google Business Profile checklist to fill out every section, with Los Angeles tips for service areas, parking, entrances and multilingual customers.",
  date: "2026-10-03",
  body: [
    "Most Google Business Profiles we see are about half finished. A name, a phone number, maybe one photo from three years ago. The rest is blank.",
    "That matters, because Google says local results are based on **relevance, distance and prominence**. A complete profile helps with relevance, and it gives customers the details they need to choose you.",
    "Here is a practical checklist, in the order we would work through it. You can finish most of it in one afternoon. If you would rather have it done for you, see our [Google Business Profile optimization](/services/google-business-profile-optimization) service.",
    "## 1. Name, category and contact details",
    "Start with the basics, and get them exactly right.",
    "- **Business name:** use your real, everyday name, the one on your sign and your invoices. Do not stuff in keywords or neighborhoods. Google's guidelines are clear that the name should match your real-world identity.\n- **Primary category:** pick the one that describes your main service, not the broadest option. Add secondary categories only for things you truly offer.\n- **Phone number:** use a number that answers during business hours, and keep it the same everywhere you are listed.\n- **Website:** link to the page that best matches the profile. For a single location, the homepage is usually fine.",
    "Consistent details across the web are called NAP (name, address, phone). It is worth getting right before anything else.",
    "## 2. Storefront or service area: choose honestly",
    "This is the section Los Angeles businesses get wrong most often.",
    "If customers visit your location, you are a **storefront**. Show your address and your hours. If you travel to customers, like a plumber, cleaner or mobile groomer, you are a **service-area business**. In that case you can hide your address and list the areas you serve.",
    "Say you run a plumbing company based in Northridge. You would list the neighborhoods and cities you actually drive to, such as the Valley, Woodland Hills or Calabasas. Do not list every corner of Los Angeles County just to look bigger. Keep it to places you can realistically reach.",
    "Never use a P.O. box or a fake address. It can get your profile suspended.",
    "## 3. Hours, with real Los Angeles details",
    "Set your regular hours first. Then add **special hours** for holidays and any days you close early.",
    "Wrong hours are one of the quickest ways to lose a customer. Someone drives across the Valley, finds the door locked, and leaves a bad review.",
    "If you serve people by appointment, say so in your description. If you have a split schedule, such as a midday break, enter both blocks.",
    "## 4. Description, services and attributes",
    "Your description is your short pitch. Write it for a person, not a search engine.",
    "- Say what you do, who you do it for and where you do it.\n- Mention what makes you different in plain words.\n- Skip phone numbers, links and special offers in the text.",
    "Next, fill out the **services section**. List each service with a short, clear description. We cover this in detail in our guide to [what the services section does](/blog/google-business-profile-services-section-explained).",
    "Then add **attributes**, the little tags that appear on your profile. Choose only the ones that apply and that you can back up, such as accessibility features, payment options or ownership details. Where Google offers an attribute for languages spoken, add it.",
    "## 5. Los Angeles tips: parking, entrances and languages",
    "Getting to a business in LA is half the battle. Help your customers out.",
    "- **Parking:** mention where to park. Is there a lot behind the building, street parking, or a validated garage?\n- **Entrance:** if your suite is in a shopping center or an office building, say which side the door is on, or which floor. Add a photo of the entrance.\n- **Accessibility:** add the accessibility attributes that are accurate for your location.\n- **Languages:** if your team speaks Spanish, Armenian, Korean, Farsi or another language, say so in your description and replies. Customers notice.",
    "These small details often decide whether someone walks in or goes to the next result.",
    "## 6. Photos, posts and Q&A",
    "Add real photos. Include the outside, the inside, your team and your work. Photos of your actual place and people beat stock images every time.",
    "Aim to add new photos on a regular schedule, even if it is only a few each month. A profile that looks active feels more trustworthy.",
    "Use **posts** to share updates, offers and events. They are quick to write and they show customers you are open for business.",
    "Where the **questions and answers** feature is available to you, add the questions customers ask most, and answer them yourself. If it is not available, put those same answers in the FAQ section of your website.",
    "## 7. Reviews: ask, reply, repeat",
    "Reviews are part of prominence, and they are also what customers read before they call. Ask happy customers after a job is done, and make it easy by sending a direct link. Our post on [getting more Google reviews without being pushy](/blog/how-to-get-more-google-reviews-without-being-pushy) has simple scripts.",
    "Reply to every review, good or bad. Keep replies short, polite and specific. If a customer wrote in another language, you can reply in it.",
    "Never offer money or gifts in exchange for reviews, and do not review your own business.",
    "## Your next step",
    "Print this list and work through it one section at a time. Then check your profile again each quarter, because hours, photos and services change.",
    "If you are in the Valley, our [San Fernando Valley](/areas/san-fernando-valley) page explains how we work with local owners. For the bigger picture, see our [local SEO](/services/local-seo) service.",
    "Want a second pair of eyes on your profile? Book a [free strategy call](/contact) and we will walk through it with you. Our goal is to get clients into the top 3 of Google Maps within 90 days, and we refund you in full if we miss.",
  ],
};

export default post;
