import type { BlogPost } from "@/lib/types";

const post: BlogPost = {
  slug: "google-business-profile-services-section-explained",
  title: "Google Business Profile Services Section Explained",
  metaTitle: "Google Business Profile Services Section Guide | Lucros Results",
  description:
    "Learn what the Google Business Profile services section is, how it differs from categories and products, and how to write service names customers understand.",
  date: "2026-10-03",
  body: [
    "Most business owners fill out their Google Business Profile once and never look at it again. The services section is one of the parts that gets skipped, or filled with whatever Google suggested.",
    "That is a missed chance. The services section is where you tell customers, in plain words, exactly what you do before they ever call.",
    "This guide explains what it is, how it differs from categories and products, and how to write it well. The exact fields you see can vary by business type, so check your own dashboard as you read.",
    "## What the services section actually is",
    "The services section is a list of the specific things you offer, shown on your profile. Each item can have a name and, in many cases, a short description and sometimes a price.",
    "Think of it as the menu of your business. A customer scrolling on their phone can see what you do without opening your website.",
    "Google also reads your profile to understand what you are about. Clear, specific services help show **relevance**, which is one of the three things Google says it uses for local results, along with distance and prominence.",
    "## Services vs. categories vs. products",
    "These three get mixed up all the time. Here is the simple difference.",
    "- **Categories** describe what kind of business you are. Your main category is the most important label on the profile.\n- **Services** describe the specific jobs you do.\n- **Products** describe items you sell, with photos and details.",
    "Say you run a plumbing company in Northridge. Your category is plumber. Your services are things like water heater replacement, drain cleaning and leak repair.",
    "Services are usually tied to your categories, so picking the right category comes first. We cover that in our guide on [how to pick the right Google Business Profile category](/blog/how-to-pick-the-right-google-business-profile-category).",
    "## Write service names the way customers search",
    "Use the words your customers use, not your industry's internal terms. People type what they need, not what your trade calls it.",
    "A few simple rules:",
    "- Be specific. \"Emergency water heater repair\" beats \"Plumbing services.\"\n- Use everyday language. \"Teeth whitening\" is clearer than a clinical product name.\n- Keep each name short, usually a few words.\n- One service per entry. Do not cram five jobs into one line.\n- Skip made-up brand names unless customers already know them.",
    "A quick test: would a neighbor understand this without asking you what it means? If not, rewrite it.",
    "## Add short descriptions that answer one question",
    "If your profile lets you add a description, use it. Keep it to a sentence or two.",
    "Good descriptions answer the question a customer is really asking: what is included, who is it for, and what happens next.",
    "Here is a hypothetical example for a hair salon in Woodland Hills. \"Balayage color: hand-painted highlights for a soft, natural look. Includes a toner and blow dry.\" It is clear, honest and easy to scan.",
    "Write for a person, not a search engine. Repeating the same keyword over and over reads badly and does not help.",
    "## What to include and what to avoid",
    "Include the services that bring you the most business, and the ones you want more of. Those are the jobs you would happily book tomorrow.",
    "Also include the services people often do not realize you offer. If you handle commercial work as well as residential, say so.",
    "Avoid a few common mistakes:",
    "- Listing services you do not actually perform just to look bigger.\n- Stuffing city names or keywords into every service name.\n- Promising prices or deals you cannot honor. If you list a price, keep it current.\n- Copying competitor wording word for word.\n- Using vague labels like \"Solutions\" or \"Consulting\" with no detail.",
    "Honest and specific wins. A profile that matches what customers find when they call builds trust, and trust is what turns a view into a lead.",
    "## Service businesses vs. retail",
    "The section works a little differently depending on what you do.",
    "**Service businesses** like plumbers, dentists, lawyers and salons get the most from it. Your services are your product, so a detailed list can do a lot of work. A contractor in Calabasas might list kitchen remodels, bathroom remodels and room additions as separate entries.",
    "**Retail and product-based businesses** usually lean on the products section more. You might still have a few services, such as alterations, delivery or in-store pickup. List those, and use products for the items on your shelves.",
    "Some business types see different options or none at all in the services area. If you do not see it, that is normal. Focus on your categories, description and photos instead.",
    "## Keep it updated",
    "Your services change. New offers get added, old ones get dropped, and seasons shift what people want.",
    "Set a reminder to review the section every few months. Add anything new, remove anything you no longer do, and check that prices are still right.",
    "Update it any time you launch a new service, too. It takes a few minutes and keeps your profile matching reality.",
    "## Your next steps this week",
    "Open your profile and look at what is listed today. Then do these three things.",
    "- Compare your services to your real top five jobs.\n- Rewrite any vague names in plain customer language.\n- Add a one or two sentence description to each one.",
    "The services section is one piece of a complete profile. If you want the full picture, learn more about our [Google Business Profile optimization](/services/google-business-profile-optimization) work for [Los Angeles](/losangeles) businesses.",
    "A strong profile is also a lead engine. Pair it with a plan for [lead generation](/services/lead-generation) so the calls and messages keep coming.",
    "Want a second set of eyes on your profile? Book a [free strategy call](/contact) and we will walk through it with you.",
  ],
};

export default post;
