import type { BlogPost } from "@/lib/types";

const post: BlogPost = {
  slug: "what-to-expect-in-your-first-90-days-of-local-seo",
  title: "What to Expect in Your First 90 Days of Local SEO",
  metaTitle: "First 90 Days of Local SEO: What to Expect | Lucros Results",
  description:
    "A realistic month-by-month look at the first 90 days of local SEO: what gets done, what you will see, what slows things down, and how to measure it.",
  date: "2026-10-03",
  body: [
    "Local SEO is not a switch you flip. It is a sequence of fixes and additions that build on each other, and the results show up in stages.",
    "If you know what each month should look like, you can tell whether things are on track instead of wondering why your phone is not ringing on day ten.",
    "Here is the honest, month-by-month picture for a Los Angeles small business, including what we do, what you do, and what to watch.",
    "## Month 1: Lay the foundation",
    "The first month is mostly invisible work. You will not see much movement yet, and that is normal.",
    "Here is what happens:",
    "- **An audit** of your Google Business Profile, website, and how your business appears across the web\n- **Profile cleanup**: correcting wrong hours, adding missing details, filling out every section\n- **Category review**: choosing the right primary category and relevant secondary ones\n- **NAP consistency**: making your name, address, and phone number match everywhere",
    "Categories and NAP matter because they tell Google exactly what you are and where you are. Our guides on [picking the right category](/blog/how-to-pick-the-right-google-business-profile-category) and [Google Business Profile optimization](/services/google-business-profile-optimization) go deeper on this stage.",
    "What you will see: small changes at most. Maybe a few more profile views once the cleanup goes live. Do not judge the whole effort by month 1.",
    "## Month 2: Build prominence",
    "Google's own guidance says local results depend on **relevance, distance, and prominence**. Month 1 handled relevance. Month 2 works on prominence, which is how well known and trusted your business looks.",
    "This is where the work becomes more visible:",
    "- **Reviews**: a steady, simple system for asking happy customers\n- **Citations**: consistent listings on directories and map platforms\n- **Website signals**: clear title tags, service pages, and your location mentioned naturally\n- **Content**: service and area pages that match what people actually search",
    "Reviews are the piece owners can influence most. Ask every satisfied customer, and ask the same day while the job is fresh.",
    "What you will see: your profile starts showing up for a few more searches, and you may notice movement for nearby searches first. Progress is usually uneven, and that is fine.",
    "## Month 3: Push and measure",
    "By now the foundation is in place, so month 3 is about reinforcing what is working and fixing what is not.",
    "We look at where you appear in the **map pack** (the three businesses Google shows on the map for a search). We check which searches bring calls and which pages need strengthening. Then we adjust.",
    "This is also when results tend to become noticeable. Calls, direction requests, and website clicks are the signals that matter most. Rankings are a means to an end.",
    "We aim for the top three in Google Maps within 90 days, and if we miss, you get a full refund. We say that plainly, but we will not pretend every business moves at the same speed.",
    "## What slows things down",
    "Some delays are normal, and some you can control. The usual culprits:",
    "- **Heavy competition** in a dense area like Los Angeles, where many businesses chase the same searches\n- **Few or no reviews**, or reviews that stopped months ago\n- **Inconsistent business information** that confuses Google about who you are\n- **A thin website** with no clear page for each service\n- **Slow approvals** on your side, such as photos, details, or access to your accounts",
    "If you have wondered why a business does not appear at all, read [why your business isn't showing up on Google Maps](/blog/why-your-business-isnt-showing-up-on-google-maps).",
    "## What you need to do",
    "Local SEO is not hands-off. A few things only you can do:",
    "- Reply quickly when we ask for access, photos, or answers\n- Ask every happy customer for a review\n- Keep your hours and details accurate, especially around holidays\n- Answer your calls and messages, since a missed call is a lost lead\n- Tell us about new services or locations so we can add them",
    "Say you run a plumbing company in Northridge. If you send us job photos and ask each customer for a review, we have far more to work with than if you leave everything to us.",
    "## How to measure progress",
    "Do not judge success by one ranking check. Your own location, device, and the time of day change what you see.",
    "Track these three things each month:",
    "- **Calls**: from your profile and your website\n- **Direction requests**: a strong sign that people are heading to you\n- **Map pack position**: for your main services, checked in the areas you serve",
    "Google Business Profile shows calls and direction requests in its performance data. Write the numbers down at the start so you have something to compare against.",
    "## Where to go from here",
    "Ninety days is enough to build a solid base and see real movement, but local SEO keeps paying off when you maintain it. Our [local SEO service](/services/local-seo) is built around this timeline, and we work with businesses across places like [Porter Ranch](/areas/porter-ranch).",
    "If you want a plan tailored to your business, book a [free strategy call](/contact) and we will walk through what month 1 would look like for you.",
  ],
};

export default post;
