import type { BlogPost } from "@/lib/types";

const post: BlogPost = {
  slug: "why-your-business-isnt-showing-up-on-google-maps",
  title: "Why Your Business Isn’t Showing Up on Google Maps",
  metaTitle: "Why Your Business Isn’t on Google Maps | Lucros Results",
  description:
    "Not showing up on Google Maps? See the common reasons local businesses miss the map pack and run a simple diagnostic this week to find what holds you back.",
  date: "2026-10-03",
  body: [
    "You search for your own services on your phone, scroll through the map results, and your business is nowhere to be seen. Meanwhile a competitor with a worse website is sitting right at the top.",
    "That is frustrating, but it is rarely random. When a local business is missing from the **map pack** (the short list of three businesses shown with a map), there is usually a specific, fixable reason.",
    "Below are the most common causes, in the order we would check them, plus a simple diagnostic you can run this week.",
    "## First, how Google picks who shows up",
    "Google says local results are based mainly on three things: **relevance**, **distance** and **prominence**. Relevance is how well your listing matches what the person searched. Distance is how close you are to them, or to the area they named. Prominence is how well known and trusted you look, based on things like reviews and mentions around the web.",
    "You cannot change where someone is standing. You can improve the other two, and the problems below all come back to them.",
    "## Your profile is incomplete or unverified",
    "If you never finished **verifying** your Google Business Profile, it generally will not show up properly in Maps. Verification is how Google confirms you are real and located where you say you are.",
    "Even a verified profile can be thin. Check that these are filled in:",
    "- Business name, address (or service area) and hours, including holiday hours\n- Phone number and website link\n- A clear business description\n- Your services and products\n- Real photos of your work, your team and your location",
    "A bare-bones profile gives Google very little to match to a search. Our [Google Business Profile optimization](/services/google-business-profile-optimization) work starts here for a reason.",
    "## You picked the wrong category, or a weak one",
    "Your **primary category** is one of the strongest signals about what you do. If you run a plumbing company but chose something vague like \"Contractor,\" you are asking Google to guess.",
    "Pick the most specific category that describes your main money-making service. Then add a few secondary categories for the other things you genuinely offer. Do not stuff in categories that do not fit. That tends to confuse the listing rather than help it.",
    "## Your name, address and phone do not match everywhere",
    "Google cross-checks your business details against other sites. If your name is spelled one way on your profile, another way on Yelp, and your old address still sits on a directory, the mismatch can lower trust in your listing.",
    "This is called **NAP consistency** (name, address, phone). Pick one exact format and use it everywhere. Suite numbers, abbreviations and old phone numbers are the usual culprits. We cover it in more depth in [what NAP is and why it matters](/blog/what-is-nap-and-why-it-matters-for-local-seo).",
    "## You have few or no reviews",
    "Reviews are a big part of prominence. A listing with little feedback looks unproven next to competitors with a steady stream of recent, detailed reviews.",
    "There is no magic number to hit. What matters is that you keep earning reviews over time, that they are recent, and that real customers describe real work in their own words. Always reply to them, good or bad. Never buy or fake reviews, because that can get a listing penalized.",
    "## Your website does not back up your listing",
    "Google looks at your website to confirm what your profile says. If your site is slow, hard to use on a phone, or never mentions the services and the city you want to be found for, it gives your listing little support.",
    "Make sure each core service has its own page, your address and phone match your profile, and your page titles say what you do and where. This is the everyday work of [local SEO](/services/local-seo).",
    "## Your service area or location is working against you",
    "Distance matters. A business that is far from the center of the area being searched will often lose to one nearby, even if the far one is stronger in other ways.",
    "Service area settings matter too. If you travel to customers and do not show a public address, make sure you have set a realistic service area rather than a huge list of cities. Say you run a landscaping company in Northridge. Listing every city in Southern California will not make you appear in all of them, and it can look unfocused.",
    "A virtual office or shared address that is not truly staffed by you can also cause trouble. Google expects a real, eligible location.",
    "## Your listing is suspended or flagged",
    "Sometimes the answer is simply that the listing has been **suspended** or marked as having a problem. Common triggers include a keyword-stuffed business name, an address that does not qualify, or edits that looked like spam.",
    "Log in to your profile and look for any warning banner or notice. If there is one, follow Google’s instructions to submit a reappeal with accurate proof of your business, and do not create a duplicate listing to get around it.",
    "## A simple diagnostic to run this week",
    "You can do this in under an hour. Work through it in order:",
    "- **Search like a customer.** Use your phone, search your main service plus your city, and note who appears and where you rank. Repeat for two or three nearby areas.\n- **Search your business name.** If you do not appear even then, suspect verification, suspension or a duplicate listing.\n- **Audit your profile.** Check verification, primary category, hours, services, description and photos.\n- **Compare to the top three.** Look at their categories, review count and recency, photos and websites. Note the biggest gaps.\n- **Check your details elsewhere.** Search your phone number and address, and write down every place the name, address or phone is different.\n- **Check your website.** Does it clearly say what you do and where, and does it load fast on a phone?",
    "Write down what you find and fix the biggest gap first. Most businesses discover two or three issues, not twenty.",
    "## Where to go from here",
    "Getting onto the map is usually a matter of fixing the basics and then staying consistent. If you serve customers around the Valley, our [San Fernando Valley area page](/areas/san-fernando-valley) explains how we approach the neighborhoods we work in.",
    "If you would rather have someone run the diagnostic with you, we are happy to help. Our goal is to get clients into the top three Google Maps results within 90 days, and if we miss, you get a full refund. Grab a [free strategy call](/contact) and we will look at your listing together.",
  ],
};

export default post;
